// File generated by hand from the Firebase console's own config files, not by the FlutterFire
// CLI — `flutterfire configure` needs an interactive Firebase login, which a checkout cannot be
// made to depend on. The values are copied verbatim from `android/app/google-services.json` and
// `ios/Runner/GoogleService-Info.plist`; if either of those is ever re-downloaded, this file has
// to be updated in step with it.
//
// It lives at the CLI's default path so that a later `flutterfire configure` overwrites this
// file rather than leaving a second, disagreeing copy behind.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// The Firebase config for whichever platform the app is running on.
///
/// Only Android and iOS are registered in the `circle360-ac46d` project, which is all the app
/// needs: the phone app is the only build that touches Firebase at all. The web build is the
/// marketing site and never reaches this file — `lib/boot/mobile_boot.dart` keeps the whole app
/// tree, and this import with it, out of the dart2js output.
///
/// Usage:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6Sk_lB9suT422Cy7I1bIpUEw7QRg2lE',
    appId: '1:470770545311:android:42880ea6f0bf15688d28aa',
    messagingSenderId: '470770545311',
    projectId: 'circle360-ac46d',
    storageBucket: 'circle360-ac46d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQR6lHf2FJYKQCUMU_l-ZPkbRNHjgIiOM',
    appId: '1:470770545311:ios:e11f7608b393afbe8d28aa',
    messagingSenderId: '470770545311',
    projectId: 'circle360-ac46d',
    storageBucket: 'circle360-ac46d.firebasestorage.app',
    iosBundleId: 'com.spacewire.circle360',
  );
}
